spring:
  application:
    name:spring-ai-chat
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://111.231.63.169:3306/spring_ai_chat?autoReconnect=true&serverTimezone=UTC%2B8&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: jQ^kd9I28MfWM9p#

  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379

  ai:
    openai:
      # ds 提供的 API 密钥
      api-key: sk-d0772cb5fef14e49a99c37e29db642c7
      #ds 开放平台地址
      base-url: https://api.deepseek.com
      chat:
        options:
          # 模型名称。deepseek-chat 使用的是 V3 模型，deepseek-reasoner 使用的是 R1 模型
          model: deepseek-chat
          # 多样化系数。常用值在0.1-1.0之间，值越大回答越多样化，推荐设置0.7。
          temperature: 0.7
          # 限制 Token 的用量
          # max-tokens: 500
    zhipuai:
      api-key: 8e3ee8d0bf6049e88e14e7edd0f04ddc.2rUtcBtRqFISv9U2
      base-url: https://open.bigmodel.cn/api/paas
      chat:
        options:
          model: GLM-4-Flash
          temperature: 0.7
          max-tokens: 1024
    chat:
      memory:
        repository:
          jdbc:
            schema: classpath:/schema/mysql.sql  # 建表的 SQL 脚本
            # 是否初始化表结构，可选值包括：
              # 1. embedded - 仅针对嵌入式数据库自动创建表。默认值
              # 2. always - 任意数据库都强制建表。首次执行推荐
              # 3. never - 禁用自动建表。首次执行后推荐
            initialize-schema: always

logging:
  level:
    org.springframework: debug